# Generated by Django 3.1.4 on 2021-01-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_auto_20210101_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=30, verbose_name='La direccion'),
        ),
    ]
